
$(function(){ 
  $('button#need-help').on('click',function(){
    $('.types-of-help').show();
    $('.need-help').hide();
    });
});
$(function(){ 
  $('button#know-someone').on('click',function(){
    $('.types-of-help').show();
    $('.need-help').hide();
    });
}); 
$(function(){ 
  $('button#dont-know').on('click',function(){
    $('.need-help').show();
    $('.types-of-help').hide();
    });
}); 